### ISSUE TITLE
회원가입 페이지 password 눈 아이콘 작동 오류

### ISSUE THREAD

**Issue by jinjintv** [FRONTENDSCHOOL10/Trinity#40]
name: 회원가입 페이지 password 눈 아이콘 작동 안함
about: 아무리 고쳐도 보이지가 않아서... issue로 올립니다
title: ''
labels: ''
assignees: ''

---

**이슈 설명**
회원가입 페이지 password-toggle-icon이 클릭으로 이미지는 바뀌지만 input type을 text로 바꾸는 기능이 동작하지 않아 수정이 필요함...

**Comment by EraMorgett4** [comment]
![image](https://github.com/user-attachments/assets/b21d1f8f-bbf0-41b4-a402-f90d1f338ed9)
signUp.js의 togglePasswordVisibility에서 element.previousElementSibling이 가리키는 것이 input이 아닌, p였음을 확인했습니다.
때문에 위 케이스에서 사용하려면 previousElementSibling을 위 사진처럼 연달아 3번 쓰는 기괴한 코드를 작성하거나,
아예 getNode등으로 해당 input을 긁어오는 방법으로 작성하면 될 것 같습니다.

**Comment by EraMorgett4** [comment]
const pwInput = getNode('#user-pw"); 로 긁어와서
조건문 안에서
pwInput.type = 'text';
이런식으로 바꾸시면 될듯함니당
